name: 'mihomo test'
on: [workflow_dispatch]
jobs:
  mihomo-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out mieru repository code
        uses: actions/checkout@v4
        with:
          path: mieru
      - name: Check out mihomo repository code
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/mihomo
          ref: Alpha
          path: mihomo
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: mihomo/go.mod
      - name: Update mieru reference
        working-directory: mihomo
        run: echo "replace github.com/enfein/mieru/v3 => ../mieru" >> go.mod
      - name: Run go mod tidy
        working-directory: mihomo
        run: go mod tidy
      - name: Show go mod diff
        working-directory: mihomo
        run: git --no-pager diff
      - name: Build mihomo
        working-directory: mihomo
        run: make linux-amd64-compatible
